test:
  name: 123
  age: 12
  sex: "男"


mybatis:
  typeAliasesPackage: com.springboot.tool.core.model.dataobj
  mapperLocations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-handlers-package: com.springboot.tool.core.model.enums.handler


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      host: localhost
      port: 6379
      password:
      timeout: 1000
      database: 0
      jedis:
        pool:
          max-active: 10
          max-idle: 10
          max-wait: 100





